on:
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  email:
    runs-on: ubuntu-latest # Use latest Ubuntu virtual machine

    permissions:
      id-token: write  # Needed for Workload Identity Federation
      contents: read   # Needed if you want to read from the repo (optional here)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/698897136000/locations/global/workloadIdentityPools/prizeversity-wif/providers/github '
          service_account: 'gmail-sender@prizeversity-461906.iam.gserviceaccount.com '
          export_environment_variables: true

      - name: Install Dependencies
        run: npm install

      - name: Send Email
        run: node send-email.js
